code clean up
onemen/TabMixPlus pull request #7
Opened 2021-01-15 09:01 UTC by 117649

I hope this time it is right.

2021-01-15 12:13 UTC, onemen commented
It doesn't look right to me, the PR should contain only your last commit (https://github.com/onemen/TabMixPlus/pull/7/commits/6d4c93014a884c9a8c965e4304e556f6c62f9f7d) 
this is the only change you made since you last pull

2021-01-15 15:13 UTC, 117649 commented
Now nail it.

2021-01-19 08:51 UTC, onemen requested changes
Thank you, just some minor changes
- Replace https://github.com/onemen/TabMixPlus/pull/7/commits/171f7052870a9b6e8fe6c81bb2e2517151116714 with commit that address the fix according to my comment.
- Move styles changes from: https://github.com/onemen/TabMixPlus/pull/7/commits/779ab829ec8515ba05f36073138c5b656d060211,  https://github.com/onemen/TabMixPlus/pull/7/commits/cc5f2b390229fc5463c1bb0ffca7924051f0af76 to separate PR

2021-01-19 08:51 UTC, onemen commented on addon/chrome/content/preferences/prefs-ce.js
> -    function updateAttribute(name, value) {
Please Don't undo all my changes :)
The only bug is in updateAttribute function just replace it with this code and prefs window should work

**new function**
```js
    const updateAttribute = (name, value) => {
      if (!this.hasAttribute(name)) {
        this.setAttribute(name, value);
      }
    };
```

**diff**
```diff
-    function updateAttribute(name, value) {
-      if (this.hasAttribute(name)) {
+    const updateAttribute = (name, value) => {
+      if (!this.hasAttribute(name)) {
         this.setAttribute(name, value);
       }
-    }
+    };
```

2021-01-19 15:11 UTC, merged